version: 2
jobs:
  build:
    docker:
      - image: node:8.6
    steps:
      - checkout
      - run: sudo npm install -g npm@5.x.x
      - restore_cache:
          key: speed-commit-msg-hook-{{ checksum "package.json" }}
      - run: npm install
      - run: npm run build
      - save_cache:
          key: speed-commit-msg-hook-{{ checksum "package.json" }}
          paths:
            - node_modules
  test:
    docker:
      - image: circleci/node:6.10
    steps:
    steps:
      - checkout
      - run: sudo npm install -g npm@5.x.x
      - restore_cache:
          key: speed-commit-msg-hook-{{ checksum "package.json" }}
      - run: npm install
      - run: npm test
      - save_cache:
          key: speed-commit-msg-hook-{{ checksum "package.json" }}
          paths:
            - node_modules

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test