version: 2
jobs:
  build:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run: sudo npm install -g npm@3.x.x
      - restore_cache:
          key: speed-commit-msg-hook-{{ checksum "package.json" }}
      - run: npm install
      - run: npm run build
      - save_cache:
          key: speed-commit-msg-hook-{{ checksum "package.json" }}
          paths:
            - node_modules
  test:
    docker:
      - image: circleci/node:6.9.5
    steps:
      - checkout
      - restore_cache:
          key: speed-commit-msg-hook-{{ checksum "package.json" }}
      - run: npm test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test